/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.stick.panel;

/**
 *
 * @author jonathan
 */
public class StickPanel extends javax.swing.JFrame {

    /**
     * Creates new form StickPanel
     */    
    
    public StickPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AptWindow = new javax.swing.JPanel();
        txtNamePac = new javax.swing.JTextField();
        txtNameDr = new javax.swing.JTextField();
        lblApt = new javax.swing.JLabel();
        lblNumApt = new javax.swing.JLabel();
        descWindow = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        AptWindow1 = new javax.swing.JPanel();
        txtNamePac1 = new javax.swing.JTextField();
        txtNameDr1 = new javax.swing.JTextField();
        lblApt1 = new javax.swing.JLabel();
        lblNumApt1 = new javax.swing.JLabel();
        descWindow1 = new javax.swing.JScrollPane();
        txtDesc1 = new javax.swing.JTextArea();
        AptWindow2 = new javax.swing.JPanel();
        txtNamePac2 = new javax.swing.JTextField();
        txtNameDr2 = new javax.swing.JTextField();
        lblApt2 = new javax.swing.JLabel();
        lblNumApt2 = new javax.swing.JLabel();
        descWindow2 = new javax.swing.JScrollPane();
        txtDesc2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximumSize(AptWindow.getMaximumSize());
        setResizable(false);

        AptWindow.setBackground(new java.awt.Color(196, 202, 198));
        AptWindow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtNamePac.setBackground(new java.awt.Color(57, 117, 117));
        txtNamePac.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtNamePac.setForeground(new java.awt.Color(255, 255, 255));
        txtNamePac.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNamePac.setText("VERONICA");
        txtNamePac.setAutoscrolls(false);
        txtNamePac.setBorder(null);
        txtNamePac.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNamePac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamePacActionPerformed(evt);
            }
        });

        txtNameDr.setBackground(new java.awt.Color(174, 173, 171));
        txtNameDr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNameDr.setText("DRº DENIS");
        txtNameDr.setBorder(null);
        txtNameDr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameDrActionPerformed(evt);
            }
        });

        lblApt.setBackground(new java.awt.Color(53, 119, 117));
        lblApt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblApt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApt.setText("APTO.");

        lblNumApt.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblNumApt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumApt.setText("1");

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        txtDesc.setText("ABDOMINOPLASTIA\n");
        descWindow.setViewportView(txtDesc);

        javax.swing.GroupLayout AptWindowLayout = new javax.swing.GroupLayout(AptWindow);
        AptWindow.setLayout(AptWindowLayout);
        AptWindowLayout.setHorizontalGroup(
            AptWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AptWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AptWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AptWindowLayout.createSequentialGroup()
                        .addGroup(AptWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblApt, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumApt, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AptWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNameDr)
                            .addComponent(txtNamePac)))
                    .addComponent(descWindow, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))
                .addContainerGap())
        );
        AptWindowLayout.setVerticalGroup(
            AptWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AptWindowLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AptWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblApt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamePac, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AptWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNumApt)
                    .addComponent(txtNameDr, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        AptWindow1.setBackground(new java.awt.Color(196, 202, 198));
        AptWindow1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtNamePac1.setBackground(new java.awt.Color(57, 117, 117));
        txtNamePac1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtNamePac1.setForeground(new java.awt.Color(255, 255, 255));
        txtNamePac1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNamePac1.setText("VERONICA");
        txtNamePac1.setAutoscrolls(false);
        txtNamePac1.setBorder(null);
        txtNamePac1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNamePac1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamePac1ActionPerformed(evt);
            }
        });

        txtNameDr1.setBackground(new java.awt.Color(174, 173, 171));
        txtNameDr1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNameDr1.setText("DRº DENIS");
        txtNameDr1.setBorder(null);
        txtNameDr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameDr1ActionPerformed(evt);
            }
        });

        lblApt1.setBackground(new java.awt.Color(53, 119, 117));
        lblApt1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblApt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApt1.setText("APTO.");

        lblNumApt1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblNumApt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumApt1.setText("1");

        txtDesc1.setColumns(20);
        txtDesc1.setRows(5);
        txtDesc1.setText("ABDOMINOPLASTIA\n");
        descWindow1.setViewportView(txtDesc1);

        javax.swing.GroupLayout AptWindow1Layout = new javax.swing.GroupLayout(AptWindow1);
        AptWindow1.setLayout(AptWindow1Layout);
        AptWindow1Layout.setHorizontalGroup(
            AptWindow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AptWindow1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AptWindow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AptWindow1Layout.createSequentialGroup()
                        .addGroup(AptWindow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblApt1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumApt1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AptWindow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNameDr1)
                            .addComponent(txtNamePac1)))
                    .addComponent(descWindow1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
                .addContainerGap())
        );
        AptWindow1Layout.setVerticalGroup(
            AptWindow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AptWindow1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AptWindow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblApt1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamePac1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AptWindow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNumApt1)
                    .addComponent(txtNameDr1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descWindow1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        AptWindow2.setBackground(new java.awt.Color(196, 202, 198));
        AptWindow2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtNamePac2.setBackground(new java.awt.Color(57, 117, 117));
        txtNamePac2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtNamePac2.setForeground(new java.awt.Color(255, 255, 255));
        txtNamePac2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNamePac2.setText("VERONICA");
        txtNamePac2.setAutoscrolls(false);
        txtNamePac2.setBorder(null);
        txtNamePac2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNamePac2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamePac2ActionPerformed(evt);
            }
        });

        txtNameDr2.setBackground(new java.awt.Color(174, 173, 171));
        txtNameDr2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNameDr2.setText("DRº DENIS");
        txtNameDr2.setBorder(null);
        txtNameDr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameDr2ActionPerformed(evt);
            }
        });

        lblApt2.setBackground(new java.awt.Color(53, 119, 117));
        lblApt2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblApt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApt2.setText("APTO.");

        lblNumApt2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblNumApt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumApt2.setText("1");

        txtDesc2.setColumns(20);
        txtDesc2.setRows(5);
        txtDesc2.setText("ABDOMINOPLASTIA\n");
        descWindow2.setViewportView(txtDesc2);

        javax.swing.GroupLayout AptWindow2Layout = new javax.swing.GroupLayout(AptWindow2);
        AptWindow2.setLayout(AptWindow2Layout);
        AptWindow2Layout.setHorizontalGroup(
            AptWindow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AptWindow2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AptWindow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AptWindow2Layout.createSequentialGroup()
                        .addGroup(AptWindow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblApt2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumApt2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AptWindow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNameDr2)
                            .addComponent(txtNamePac2)))
                    .addComponent(descWindow2, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
                .addContainerGap())
        );
        AptWindow2Layout.setVerticalGroup(
            AptWindow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AptWindow2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AptWindow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblApt2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamePac2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AptWindow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNumApt2)
                    .addComponent(txtNameDr2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descWindow2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AptWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AptWindow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AptWindow2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AptWindow1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AptWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AptWindow2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(684, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamePacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamePacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamePacActionPerformed

    private void txtNameDrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameDrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameDrActionPerformed

    private void txtNamePac1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamePac1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamePac1ActionPerformed

    private void txtNameDr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameDr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameDr1ActionPerformed

    private void txtNamePac2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamePac2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamePac2ActionPerformed

    private void txtNameDr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameDr2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameDr2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StickPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StickPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StickPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StickPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StickPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AptWindow;
    private javax.swing.JPanel AptWindow1;
    private javax.swing.JPanel AptWindow2;
    private javax.swing.JScrollPane descWindow;
    private javax.swing.JScrollPane descWindow1;
    private javax.swing.JScrollPane descWindow2;
    private javax.swing.JLabel lblApt;
    private javax.swing.JLabel lblApt1;
    private javax.swing.JLabel lblApt2;
    private javax.swing.JLabel lblNumApt;
    private javax.swing.JLabel lblNumApt1;
    private javax.swing.JLabel lblNumApt2;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextArea txtDesc1;
    private javax.swing.JTextArea txtDesc2;
    private javax.swing.JTextField txtNameDr;
    private javax.swing.JTextField txtNameDr1;
    private javax.swing.JTextField txtNameDr2;
    private javax.swing.JTextField txtNamePac;
    private javax.swing.JTextField txtNamePac1;
    private javax.swing.JTextField txtNamePac2;
    // End of variables declaration//GEN-END:variables
}
